modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "KGUI Properties Example"
authors = "Kneelawk"
description = "Cuddly Minecraft GUI library Properties Example."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.4.148-beta,)"
ordering = "NONE"
side = "BOTH"
